services:

  app:
    image: python:3.12
    ports:
      - 5000:5000
    volumes:
      - ../:/app
    working_dir: /app
    entrypoint: ["bash", "-c", "pip install -r requirements.txt && watchmedo auto-restart --pattern='*.py;*.html;*.css;*.js' --recursive python3 app.py"]

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo